### PR TITLE
Graft use etna

### PR DESCRIPTION
**Pull request by graft**
This strips out rails and switches to using Etna::Server. Observe the cleaner Gemfile that results!

This involved rewriting all of the existing controllers and adding specs for them. Some things may have broken.

One thing that is broken for sure is saving plots; I have elected not to fix this as I think there is a bunch of other broken stuff in plots that needs fixing ASAP, so I will do this next and leave this broken for the moment. I don't think anyone will notice anyway.

There is one failing test; I have left this in intentionally as I think the plot controller that handles this behaves incorrectly, I will fix this in the corresponding branch.

I have opted NOT to rebuild the database, which should be fine; Sequel is made to play nice with ActiveRecord anyway, so the models should be compatible. There is a new initial migration built by Sequel in db/migrations.

The old files in app/controllers and app/assets are still in place for the moment, to make rebasing easier. However, note that these will not run anymore (except for the archimedes code in app/models/archimedes/), all of the new controllers are in lib/server/controllers.

### CODE REVIEW

**Comment by jasondcater** [comment]
### General notes
  There is some syntax clean up required in the API files but I've done that in another branch.

### Essential

./lib/models/view_pane.rb
  line 56:
    'description' is not part of the table/model and causes an error. The line was part of the original model. However, it was included by mistake. Remove the 'description' item.

./config.ru
  Needs the Rack::Static line to pass the compiled js/css/img
  `use Rack::Static, urls: ['/css', '/js', '/fonts', '/img'], root: 'public'`

### Non-essential

./lib/server.rb
  line 45, 51:
    Wrap line to be less than 80 chars wide.

./lib/server/controllers/browse_controller.rb
  line 4, 14:
    Add line breaks to the argument list to make it consistant.

./lib/server/constrollers/magma_controller.rb
  line 19:
    Condense line to be less than 80 chars wide.

  line 31:
    Use capitilization and punctuation on comment.

  line 45, 58:
    Add line breaks to the argument list to make it consistant.

./lib/server/constrollers/manifest_controller.rb
  line 34, 36, 47:
    Wrap line to be less than 80 chars wide.

./lib/server/constrollers/timur_controller.rb
  line 7:
    Add parens to function definition when specifying arguments.

./lib/models/manifest.rb
  line 32:
    Wrap line to be less than 80 chars wide.

./lib/models/user.rb
  line 9-10:
    Fix odd array wrapping. Use a variable if the line it too long.

./lib/models/view_pane.rb
  line 7:
    Wrap line to be less than 80 chars wide.

**Comment by graft** [comment]
I removed the description from the db - you can use `bin/timur migrate` to update. However the first time you run this command it will fail, after which you must manually run "update schema_info set version=1"; then the migration will run.

**Comment by graft** [comment]
Re: rack::static, I have been using Apache to serve static assets from /public, so that line is not required. This is easier on the server, since it spares rack some load.

**Comment by graft** [comment]
There is a problem with the magma controller, the tsv response is not chunking correctly. Rather than solve the multiple chunking problem I will implement #158 and eliminate the magma controller.

**Comment by graft** [comment]
Ok, I updated the javascript client to phone Magma directly; this required updating Magma to support cross-origin requests, since otherwise the browser restricts to the same origin. This allowed me to ditch the magma_controller. Downloading TSVs and posting updates seems to work okay now.

**Comment by jasondcater** [comment]
This is working well. Please merge.

**Pull request merged**
