### PR TITLE
testing framework for javascript

### PR DESCRIPTION
**Pull request by dabrau**
run "npm install" to get the testing dependencies
"npm test" to run the tests

### CODE REVIEW

**Comment by graft** [comment]
This looks pretty cool - my main complaint is the rather baroque JSON fixtures you have in the middle of your tests which sometimes go on for several pages. Can we (1) either write some helper functions to slim these down a bit or (2, less good) move them to some fixtures.json file?

A nice manifest factory function could be used in many of these tests and would help clean up a lot of this code. I've been enjoying FactoryGirl in ruby, which generates test fixtures in my database, I feel certain there must be something similar for making json fixtures that can make these tests a little simpler.

**Comment by jasondcater** [comment]
Looks good. Please single quote your code and add semicolons.

**Comment by graft** [comment]
Can we merge this? Seems highly useful to get it in place...

**Comment by dabrau** [comment]
I will work on this today. I plan to get it in today or tomorrow.

**Pull request merged**
