### PR TITLE
Magma-Metis  Integration

### PR DESCRIPTION
**Pull request by coleshaw**
This is the Timur-end of the changes required for mountenta/magma#180.

Adds three new buttons for managing File and Image attributes:
* Blank the file
* Remove the file
* Link a file via a Metis path.

Also updates the Image attribute to behave similarly as the File attribute component.

### CODE REVIEW

**Comment by graft** [comment]
One thing i noted yesterday in the demo: could you pop the metis path input out into a modal? The current behavior was kind of a placeholder when i handed it off and in the future we will probably want a larger file browser component there.

**Comment by coleshaw** [comment]
Re: modal, yup, I could do that.

I'm stuck trying to get the Magma gem to work with CI and bundle (also running into the same problem with `monoetna`). It would be helpful to switch to Etna Client or put Magma into RubyGems...so perhaps ignore the Ruby checks for now. Tests pass locally.

**Comment by coleshaw** [comment]
Changed to modal, it looks like this:

Screenshot from 2020-07-07 11-32-05

**Comment by graft** [comment]
The help in the modal is useful but maybe a bit aggressive for non-first-time users; could it go into the documentation repo + a small help link in the UI? Also looks like the modal breaks some styles...

**Comment by coleshaw** [comment]
Do you mean the input styles? Yeah, the modal lives outside of the `attribute` class tree, so I think we would have to re-create any of the styling that is missing.

So the documentation is already in this PR, mountetna/monoetna#12, so I can take out parts.

**Comment by coleshaw** [comment]
Updated modal

Screenshot from 2020-07-07 12-11-44

**Comment by coleshaw** [comment]
Screenshot from 2020-07-07 12-36-24

Modal has lost more weight.

**Pull request merged**
